// CluesVault Data Constants and Default APIs

export const STORAGE_KEY = 'cluesvault_api_registry_v2';
export const AUTH_KEY = 'cluesvault_auth_v2';

export const PRODUCTS = [
  'CLUES Core',
  'CLUES: QI',
  'CLUES: Valiant',
  'CLUES: TES',
  'Heart-Recovery_Calendar',
  'Olivia-Chatbot'
];

export const DEFAULT_APIS = [
  {
    apiId: 'openai-core',
    name: 'OpenAI API',
    status: 'active',
    products: ['CLUES Core', 'CLUES: QI', 'CLUES: Valiant', 'CLUES: TES', 'Olivia-Chatbot'],
    category: 'LLM / AI',
    description: 'Generates CLUES relocation reports, QI property narratives, and powers Olivia-style assistants.',
    baseUrlProd: 'https://api.openai.com/v1',
    docsUrl: 'https://platform.openai.com/docs/api-reference',
    authMethod: 'Bearer API key',
    envProd: 'OPENAI_API_KEY',
    envDev: 'OPENAI_API_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://platform.openai.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://platform.openai.com/api-keys',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › OpenAI Production Key',
    tags: ['critical', 'paid', 'external'],
    notes: 'Monitor RPM/TPM when batch-generating large reports and Olivia conversations.',
    // NEW CREDENTIAL FIELDS
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'typeform-clues',
    name: 'Typeform',
    status: 'active',
    products: ['CLUES Core', 'CLUES: Valiant'],
    category: 'Forms / Intake',
    description: 'Collects CLUES questionnaires and pipes responses into automation (Zapier/Make).',
    baseUrlProd: 'https://api.typeform.com',
    docsUrl: 'https://developer.typeform.com',
    authMethod: 'Bearer API token',
    envProd: 'TYPEFORM_API_TOKEN',
    envDev: 'TYPEFORM_API_TOKEN_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://admin.typeform.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://admin.typeform.com/account#/section/tokens',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Typeform',
    tags: ['questionnaire', 'external'],
    notes: 'Contains sensitive lifestyle and relocation data; treat as high sensitivity.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'ors-transit',
    name: 'OpenRouteService',
    status: 'active',
    products: ['CLUES: TES'],
    category: 'Maps / Routing',
    description: 'Provides routing and travel-time estimates for the CLUES TES London transit dashboard.',
    baseUrlProd: 'https://api.openrouteservice.org',
    docsUrl: 'https://openrouteservice.org/dev/#/api-docs',
    authMethod: 'API key in header',
    envProd: 'ORS_API_KEY',
    envDev: 'ORS_API_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://dashboard.openrouteservice.org',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://dashboard.openrouteservice.org/dashboard',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › ORS',
    tags: ['maps', 'geo', 'external'],
    notes: 'Respect daily quota; avoid per-keystroke calls for route suggestions.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'weather-com',
    name: 'Weather.com API',
    status: 'testing',
    products: ['CLUES Core', 'CLUES: Valiant', 'CLUES: TES', 'Heart-Recovery_Calendar'],
    category: 'Weather / Climate',
    description: 'Provides weather and climate data for CLUES comfort scoring, TES transit comfort, and Heart-Recovery_Calendar advisories.',
    baseUrlProd: 'https://api.weather.com',
    docsUrl: 'https://weather.com/swagger-docs',
    authMethod: 'API key',
    envProd: 'WEATHER_COM_API_KEY',
    envDev: 'WEATHER_COM_API_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://weather.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://weather.com/swagger-docs',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Weather.com API',
    tags: ['climate', 'external', 'paid'],
    notes: 'Do not embed raw key in client apps; keep in env vars on server or Capacitor secure storage.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'did-streaming',
    name: 'D-ID Streaming API',
    status: 'testing',
    products: ['CLUES Core', 'Olivia-Chatbot'],
    category: 'Video / Avatar',
    description: 'Drives the interactive Olivia video chatbot that explains CLUES reports in the member dashboard.',
    baseUrlProd: 'https://api.d-id.com',
    docsUrl: 'https://docs.d-id.com/reference/overview',
    authMethod: 'API key in header',
    envProd: 'DID_API_KEY',
    envDev: 'DID_API_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://studio.d-id.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://docs.d-id.com/reference/overview',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › D-ID Streaming',
    tags: ['avatar', 'video', 'external'],
    notes: 'Use server-side proxy for tokens; do not expose API key directly in browser or mobile bundle.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'heygen-video',
    name: 'HeyGen API',
    status: 'active',
    products: ['CLUES Core', 'CLUES: QI', 'Olivia-Chatbot'],
    category: 'Video / Avatar',
    description: 'Generates pre-rendered avatar videos for CLUES marketing, report summaries, and YouTube content.',
    baseUrlProd: 'https://api.heygen.com',
    docsUrl: 'https://docs.heygen.com',
    authMethod: 'API key',
    envProd: 'HEYGEN_API_KEY',
    envDev: 'HEYGEN_API_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://app.heygen.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://app.heygen.com/settings/api-keys',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › HeyGen',
    tags: ['avatar', 'marketing', 'external'],
    notes: 'Used for asynchronous video generation, not live chat; watch usage-based billing.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'zapier-platform',
    name: 'Zapier Webhooks / Platform',
    status: 'active',
    products: ['CLUES Core', 'CLUES: QI', 'CLUES: Valiant', 'CLUES: TES'],
    category: 'Automation',
    description: 'Connects Typeform, Google Sheets, OpenAI, Stripe, and email for CLUES pipeline automation.',
    baseUrlProd: 'https://hooks.zapier.com',
    docsUrl: 'https://platform.zapier.com/docs',
    authMethod: 'Signed webhook / API key',
    envProd: 'ZAPIER_WEBHOOK_SECRET',
    envDev: 'ZAPIER_WEBHOOK_SECRET_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://zapier.com/app/zaps',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://zapier.com/app/zaps',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Zapier',
    tags: ['automation', 'webhook', 'external'],
    notes: 'Use secret tokens and IP restrictions where possible; prefer Zapier over Make.com for new flows.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'make-scenarios',
    name: 'Make.com Scenarios',
    status: 'testing',
    products: ['CLUES Core', 'CLUES: TES'],
    category: 'Automation',
    description: 'Legacy and experimental automation scenarios for CLUES questionnaires and transit dashboard.',
    baseUrlProd: 'https://eu1.make.com/api',
    docsUrl: 'https://www.make.com/en/help',
    authMethod: 'API token',
    envProd: 'MAKE_API_TOKEN',
    envDev: 'MAKE_API_TOKEN_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://eu1.make.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://eu1.make.com/organization/keys',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Make.com',
    tags: ['automation', 'legacy', 'external'],
    notes: 'Migrate legacy flows to Zapier if possible for better reliability and cost.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'google-sheets',
    name: 'Google Sheets API',
    status: 'active',
    products: ['CLUES Core', 'CLUES: QI', 'CLUES: Valiant'],
    category: 'Data / Spreadsheets',
    description: 'Central data hub for CLUES questionnaire responses, property comparisons, and report generation pipelines.',
    baseUrlProd: 'https://sheets.googleapis.com',
    docsUrl: 'https://developers.google.com/sheets/api',
    authMethod: 'OAuth2 / Service account',
    envProd: 'GOOGLE_SHEETS_SERVICE_KEY',
    envDev: 'GOOGLE_SHEETS_SERVICE_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://console.cloud.google.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://console.cloud.google.com/apis/credentials',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Google Service Account',
    tags: ['data', 'google', 'external'],
    notes: 'Use service account with least privilege; avoid personal Google accounts for production.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'quickchart-images',
    name: 'QuickChart API',
    status: 'active',
    products: ['CLUES Core', 'CLUES: Valiant', 'CLUES: TES'],
    category: 'Charts / Images',
    description: 'Renders heatmaps, radar charts, and bar graphs for CLUES and TES visualizations.',
    baseUrlProd: 'https://quickchart.io',
    docsUrl: 'https://quickchart.io/documentation/',
    authMethod: 'API key (optional for high volume)',
    envProd: 'QUICKCHART_API_KEY',
    envDev: 'QUICKCHART_API_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://quickchart.io',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://quickchart.io/documentation/',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › QuickChart API',
    tags: ['charts', 'images', 'external'],
    notes: 'Charts can be generated without auth at low volume; add key for production throughput.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'calendly-core',
    name: 'Calendly API',
    status: 'active',
    products: ['CLUES Core'],
    category: 'Bookings / Scheduling',
    description: 'Handles booking links and meeting scheduling for CLUES consultations and report reviews.',
    baseUrlProd: 'https://api.calendly.com',
    docsUrl: 'https://developer.calendly.com',
    authMethod: 'Personal access token',
    envProd: 'CALENDLY_API_TOKEN',
    envDev: 'CALENDLY_API_TOKEN_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://calendly.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://calendly.com/integrations/api_webhooks',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Calendly',
    tags: ['calendar', 'bookings', 'external'],
    notes: 'Use webhooks to trigger report workflows after a booking is created or canceled.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'stripe-core',
    name: 'Stripe API',
    status: 'active',
    products: ['CLUES Core', 'CLUES: QI'],
    category: 'Payments',
    description: 'Processes payments for CLUES report tiers, consulting, and brokerage services.',
    baseUrlProd: 'https://api.stripe.com',
    docsUrl: 'https://stripe.com/docs/api',
    authMethod: 'Secret key',
    envProd: 'STRIPE_SECRET_KEY',
    envDev: 'STRIPE_SECRET_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://dashboard.stripe.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://dashboard.stripe.com/apikeys',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Stripe Secret Key',
    tags: ['payments', 'critical', 'external'],
    notes: 'Use Stripe Checkout and Payment Links where possible; never expose secret key in client apps.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'uber-rides',
    name: 'Uber Rides API',
    status: 'planning',
    products: ['CLUES: TES'],
    category: 'Mobility / Rideshare',
    description: 'Intended for comparing Uber travel times and costs to metro/tube in TES dashboards.',
    baseUrlProd: 'https://api.uber.com',
    docsUrl: 'https://developer.uber.com/docs/riders',
    authMethod: 'OAuth2 / Server token',
    envProd: 'UBER_SERVER_TOKEN',
    envDev: 'UBER_SERVER_TOKEN_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://developer.uber.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://developer.uber.com/dashboard',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Uber API',
    tags: ['rideshare', 'mobility', 'external'],
    notes: 'Check latest Uber API program requirements; may require approved app and non-test account.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'wix-http-functions',
    name: 'Wix HTTP Functions / Backend',
    status: 'active',
    products: ['CLUES Core', 'CLUES: TES'],
    category: 'Internal Backend',
    description: 'Wix backend HTTP functions and data collections powering the CLUES front-end website and dashboards.',
    baseUrlProd: 'https://www.cluesnomad.com/_functions',
    docsUrl: 'https://dev.wix.com/docs/sdk/backend-modules/http-functions',
    authMethod: 'Wix site authentication / custom tokens',
    envProd: 'WIX_BACKEND_CONFIG',
    envDev: 'WIX_BACKEND_CONFIG_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://manage.wix.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: '',
    tokenLastRotated: '',
    secretLocation: 'Wix project settings & 1Password › CLUES › Wix Backend Notes',
    tags: ['internal', 'backend'],
    notes: 'Treat as internal API boundary between Wix front-end and external services (OpenRouteService, CLUES logic, etc.).',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'google-docs',
    name: 'Google Docs API',
    status: 'planning',
    products: ['CLUES Core', 'CLUES: QI'],
    category: 'Documents / Reports',
    description: 'Optional integration for generating and updating CLUES narrative reports as Google Docs.',
    baseUrlProd: 'https://docs.googleapis.com',
    docsUrl: 'https://developers.google.com/docs/api',
    authMethod: 'OAuth2 / Service account',
    envProd: 'GOOGLE_DOCS_SERVICE_KEY',
    envDev: 'GOOGLE_DOCS_SERVICE_KEY_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://console.cloud.google.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://console.cloud.google.com/apis/credentials',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Google Docs Service Account',
    tags: ['docs', 'reports', 'google'],
    notes: 'Future-facing; main deliverables currently Word/PDF rather than live Docs.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  },
  {
    apiId: 'gmail-api',
    name: 'Gmail API',
    status: 'planning',
    products: ['CLUES Core'],
    category: 'Email / Notifications',
    description: 'Optional direct email integration for sending CLUES reports and updates from cluesnomads@gmail.com.',
    baseUrlProd: 'https://gmail.googleapis.com',
    docsUrl: 'https://developers.google.com/gmail/api',
    authMethod: 'OAuth2 / Service account',
    envProd: 'GMAIL_API_CREDENTIALS',
    envDev: 'GMAIL_API_CREDENTIALS_DEV',
    accountEmail: 'cluesnomads@gmail.com',
    loginUrl: 'https://console.cloud.google.com',
    accountPassword: '',
    apiKeyToken: '',
    tokenPortalUrl: 'https://console.cloud.google.com/apis/credentials',
    tokenLastRotated: '',
    secretLocation: '1Password › CLUES › Gmail API Credentials',
    tags: ['email', 'google'],
    notes: 'Alternatively use Zapier/Gmail actions instead of direct API calls for simplicity.',
    userId: '',
    username: '',
    personalCode: '',
    passcode: '',
    loginCredentials: ''
  }
];
